name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust the PHP version as needed

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the Node.js version as needed

      - name: Install Node.js Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Upload Project to Ubuntu Server
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/Smashr && git pull origin main'
         
      - name: Install dependencies on server
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/Smashr && npm install && composer install && npm run build'

      - name: Recache files
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/Smashr && php artisan optimize:clear && php artisan optimize'
