name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust the PHP version as needed

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-ansi --no-progress --prefer-dist

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Upload Project to Ubuntu Server
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/igneas-api && eval "$(ssh-agent -s)" && ssh-add ~/.ssh/github-login && git pull origin main'
         
      - name: Install dependencies on server
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/igneas-api && composer install'

      - name: Recache files
        run: ssh -i ~/.ssh/id_rsa vulps@161.97.68.166 'cd /var/www/html/igneas-api && php artisan migrate && php artisan optimize:clear && php artisan optimize'
